sonar.projectKey=oasis
sonar.projectName=oasis
sonar.sources=.
sonar.language=py
sonar.host.url=http://localhost:9000
#sonar.login should be passed as environment variable
sonar.exclusions=nrt/template_test_case/plots.html
sonar.python.coverage.reportPaths=coverage.xml